In [14]:
import numpy as np
import tensorflow as tf
from tf_agents.networks.q_network import QNetwork
import tf_agents.networks.network as network
from tf_agents.specs import tensor_spec
from snake_game import SnakeGame
from scene import Scene
from scene_longer_snake import SceneLongerSnake
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Flatten, Conv2D, Input

scene = SceneLongerSnake(init_randomly=True, snake_longer_prob=0.95, length_mean=10, length_std=2)
episodes_count = 100000
random_episodes = 20000


In [15]:
from tf_agents.environments.tf_py_environment import TFPyEnvironment

env = SnakeGame(scene)
env = TFPyEnvironment(env)


In [16]:
class MyQNetwork(network.Network):
    def __init__(self,
                 input_tensor_spec,
                 action_spec,
                 name='MyQNetwork'):
        super(MyQNetwork, self).__init__(
            input_tensor_spec=input_tensor_spec,
            state_spec=(),
            name=name)
        
        self._action_spec = action_spec
        matrix_shape = input_tensor_spec[0].shape
        obstacles_shape = input_tensor_spec[1].shape
        no_body_blocks_shape = input_tensor_spec[2].shape
        
        input0 = Input(shape=matrix_shape)
        input1 = Input(shape=obstacles_shape) # Each value represents if there is a wall or the snake body in the direction, 0 - no wall, 1 - wall
        input2 = Input(shape=no_body_blocks_shape) # Each value represents how many no body blocks are in the direction
        
        conv = Conv2D(32, (2, 2), 1, activation='relu', kernel_initializer='he_normal')(input0)
        flat = Flatten()(conv)
        dense1 = Dense(128, activation='relu', kernel_initializer='he_normal')(flat)
        dense2 = Dense(32, activation='relu', kernel_initializer='he_normal')(dense1)
        
        concat = tf.keras.layers.concatenate([dense2, input1, input2])
        output = Dense(4, activation='linear')(concat)
        
        self._model = tf.keras.Model(inputs=[input0, input1, input2], outputs=output)
        
        self._model.summary()

    def call(self, observations, step_type=None, network_state=(), training=False):
        output = self._model([observations[0], observations[1], observations[2]])
        return output, network_state

q_net = MyQNetwork(
    env.observation_spec(),
    env.action_spec())


Model: "model_2"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_7 (InputLayer)        [(None, 5, 5, 4)]            0         []                            
                                                                                                  
 conv2d_2 (Conv2D)           (None, 4, 4, 32)             544       ['input_7[0][0]']             
                                                                                                  
 flatten_2 (Flatten)         (None, 512)                  0         ['conv2d_2[0][0]']            
                                                                                                  
 dense_6 (Dense)             (None, 128)                  65664     ['flatten_2[0][0]']           
                                                                                            

In [17]:
# Create the agent
from tf_agents.agents.dqn.dqn_agent import DdqnAgent
from tensorflow import keras
from keras.optimizers.legacy import Adam
from keras.losses import Huber
from tf_agents.trajectories import TimeStep

train_step_counter = tf.Variable(0)
optimizer = Adam(learning_rate=0.001)

epsilon = keras.optimizers.schedules.PolynomialDecay(
    initial_learning_rate=0.1,
    decay_steps=episodes_count,
    end_learning_rate=0.01
)

agent = DdqnAgent(
    time_step_spec=env.time_step_spec(),
    action_spec=env.action_spec(),
    q_network=q_net,
    optimizer=optimizer,
    td_errors_loss_fn=Huber(reduction="none"),
    gamma=tf.constant(0.95, dtype=tf.float32),
    train_step_counter=train_step_counter,
    epsilon_greedy=lambda: epsilon(train_step_counter)
)


Model: "model_3"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_10 (InputLayer)       [(None, 5, 5, 4)]            0         []                            
                                                                                                  
 conv2d_3 (Conv2D)           (None, 4, 4, 32)             544       ['input_10[0][0]']            
                                                                                                  
 flatten_3 (Flatten)         (None, 512)                  0         ['conv2d_3[0][0]']            
                                                                                                  
 dense_9 (Dense)             (None, 128)                  65664     ['flatten_3[0][0]']           
                                                                                            

In [18]:
# Create the replay buffer
from tf_agents.replay_buffers import tf_uniform_replay_buffer

replay_buffer = tf_uniform_replay_buffer.TFUniformReplayBuffer(
    data_spec=agent.collect_data_spec,
    batch_size=env.batch_size,
    max_length=100000
)


In [19]:
# Create the training metrics
from tf_agents.metrics import tf_metrics

train_metrics = [
    tf_metrics.NumberOfEpisodes(),
    tf_metrics.EnvironmentSteps(),
    tf_metrics.AverageReturnMetric(),
    tf_metrics.AverageEpisodeLengthMetric()
]


In [20]:
# Create the driver
from tf_agents.drivers import dynamic_step_driver

collect_driver = dynamic_step_driver.DynamicStepDriver(
    env,
    policy=agent.collect_policy,
    observers=[replay_buffer.add_batch] + train_metrics,
    num_steps=2
)

# Run a random policy to fill the replay buffer
from tf_agents.policies.random_tf_policy import RandomTFPolicy

initial_collect_policy = RandomTFPolicy(env.time_step_spec(), env.action_spec())
init_driver = dynamic_step_driver.DynamicStepDriver(
    env,
    policy=initial_collect_policy,
    observers=[replay_buffer.add_batch],
    num_steps=random_episodes
)

final_time_step, final_policy_state = init_driver.run()


In [21]:
# Create the dataset
dataset = replay_buffer.as_dataset(
    sample_batch_size=64,
    num_steps=2, # Capaz cambiar esto
    num_parallel_calls=5
).prefetch(5)


In [22]:

# Create the training loop

from tf_agents.utils.common import function
from tf_agents.trajectories import trajectory
from tf_agents.eval.metric_utils import log_metrics
import logging

logging.getLogger().setLevel(logging.INFO)

collect_driver.run = function(collect_driver.run)
agent.train = function(agent.train)

def train_agent(n_iterations):
    time_step = None
    policy_state = agent.collect_policy.get_initial_state(env.batch_size)
    iterator = iter(dataset)
    for iteration in range(n_iterations):
        time_step, policy_state = collect_driver.run(time_step, policy_state)
        trajectories, buffer_info = next(iterator)
        train_loss = agent.train(trajectories)
        if iteration % 1000 == 0:
            print("Iteration: ", iteration)
            print("Replay buffer len: " + str(replay_buffer.num_frames().numpy()))
            log_metrics(train_metrics)


In [23]:
train_agent(episodes_count)


INFO:absl: 
		 NumberOfEpisodes = 2
		 EnvironmentSteps = 2
		 AverageReturn = -60.0
		 AverageEpisodeLength = 0.5


Iteration:  0
Replay buffer len: 43702


INFO:absl: 
		 NumberOfEpisodes = 672
		 EnvironmentSteps = 2002
		 AverageReturn = -26223.0
		 AverageEpisodeLength = 5.199999809265137


Iteration:  1000
Replay buffer len: 46372


INFO:absl: 
		 NumberOfEpisodes = 914
		 EnvironmentSteps = 4002
		 AverageReturn = -35406.0
		 AverageEpisodeLength = 3.700000047683716


Iteration:  2000
Replay buffer len: 48614


INFO:absl: 
		 NumberOfEpisodes = 1044
		 EnvironmentSteps = 6002
		 AverageReturn = -40192.5
		 AverageEpisodeLength = 26.600000381469727


Iteration:  3000
Replay buffer len: 50743


INFO:absl: 
		 NumberOfEpisodes = 1172
		 EnvironmentSteps = 8002
		 AverageReturn = -44733.0
		 AverageEpisodeLength = 12.199999809265137


Iteration:  4000
Replay buffer len: 52872


INFO:absl: 
		 NumberOfEpisodes = 1266
		 EnvironmentSteps = 10002
		 AverageReturn = -48149.5
		 AverageEpisodeLength = 17.700000762939453


Iteration:  5000
Replay buffer len: 54966


INFO:absl: 
		 NumberOfEpisodes = 1381
		 EnvironmentSteps = 12002
		 AverageReturn = -52282.0
		 AverageEpisodeLength = 26.700000762939453


Iteration:  6000
Replay buffer len: 57081


INFO:absl: 
		 NumberOfEpisodes = 1492
		 EnvironmentSteps = 14002
		 AverageReturn = -56185.0
		 AverageEpisodeLength = 10.899999618530273


Iteration:  7000
Replay buffer len: 59192


INFO:absl: 
		 NumberOfEpisodes = 1609
		 EnvironmentSteps = 16002
		 AverageReturn = -60343.0
		 AverageEpisodeLength = 13.5


Iteration:  8000
Replay buffer len: 61309


INFO:absl: 
		 NumberOfEpisodes = 1744
		 EnvironmentSteps = 18002
		 AverageReturn = -65081.5
		 AverageEpisodeLength = 14.600000381469727


Iteration:  9000
Replay buffer len: 63444


INFO:absl: 
		 NumberOfEpisodes = 1866
		 EnvironmentSteps = 20002
		 AverageReturn = -69138.5
		 AverageEpisodeLength = 8.600000381469727


Iteration:  10000
Replay buffer len: 65566


INFO:absl: 
		 NumberOfEpisodes = 2003
		 EnvironmentSteps = 22002
		 AverageReturn = -73778.0
		 AverageEpisodeLength = 14.699999809265137


Iteration:  11000
Replay buffer len: 67703


INFO:absl: 
		 NumberOfEpisodes = 2127
		 EnvironmentSteps = 24002
		 AverageReturn = -77765.0
		 AverageEpisodeLength = 13.300000190734863


Iteration:  12000
Replay buffer len: 69826


INFO:absl: 
		 NumberOfEpisodes = 2232
		 EnvironmentSteps = 26002
		 AverageReturn = -80835.0
		 AverageEpisodeLength = 10.5


Iteration:  13000
Replay buffer len: 71932


INFO:absl: 
		 NumberOfEpisodes = 2358
		 EnvironmentSteps = 28002
		 AverageReturn = -84732.5
		 AverageEpisodeLength = 17.0


Iteration:  14000
Replay buffer len: 74058


INFO:absl: 
		 NumberOfEpisodes = 2499
		 EnvironmentSteps = 30002
		 AverageReturn = -89143.5
		 AverageEpisodeLength = 7.400000095367432


Iteration:  15000
Replay buffer len: 76199


INFO:absl: 
		 NumberOfEpisodes = 2634
		 EnvironmentSteps = 32002
		 AverageReturn = -93335.0
		 AverageEpisodeLength = 14.399999618530273


Iteration:  16000
Replay buffer len: 78334


INFO:absl: 
		 NumberOfEpisodes = 2760
		 EnvironmentSteps = 34002
		 AverageReturn = -97050.0
		 AverageEpisodeLength = 14.800000190734863


Iteration:  17000
Replay buffer len: 80460


INFO:absl: 
		 NumberOfEpisodes = 2880
		 EnvironmentSteps = 36002
		 AverageReturn = -100528.0
		 AverageEpisodeLength = 17.100000381469727


Iteration:  18000
Replay buffer len: 82580


INFO:absl: 
		 NumberOfEpisodes = 3007
		 EnvironmentSteps = 38002
		 AverageReturn = -104190.0
		 AverageEpisodeLength = 12.600000381469727


Iteration:  19000
Replay buffer len: 84707


INFO:absl: 
		 NumberOfEpisodes = 3126
		 EnvironmentSteps = 40002
		 AverageReturn = -107346.5
		 AverageEpisodeLength = 20.399999618530273


Iteration:  20000
Replay buffer len: 86826


INFO:absl: 
		 NumberOfEpisodes = 3238
		 EnvironmentSteps = 42002
		 AverageReturn = -110384.0
		 AverageEpisodeLength = 17.5


Iteration:  21000
Replay buffer len: 88938


INFO:absl: 
		 NumberOfEpisodes = 3369
		 EnvironmentSteps = 44002
		 AverageReturn = -114256.0
		 AverageEpisodeLength = 10.5


Iteration:  22000
Replay buffer len: 91069


INFO:absl: 
		 NumberOfEpisodes = 3494
		 EnvironmentSteps = 46002
		 AverageReturn = -117744.0
		 AverageEpisodeLength = 18.899999618530273


Iteration:  23000
Replay buffer len: 93194


INFO:absl: 
		 NumberOfEpisodes = 3607
		 EnvironmentSteps = 48002
		 AverageReturn = -120766.5
		 AverageEpisodeLength = 17.5


Iteration:  24000
Replay buffer len: 95307


INFO:absl: 
		 NumberOfEpisodes = 3714
		 EnvironmentSteps = 50002
		 AverageReturn = -123244.5
		 AverageEpisodeLength = 14.0


Iteration:  25000
Replay buffer len: 97414


INFO:absl: 
		 NumberOfEpisodes = 3826
		 EnvironmentSteps = 52002
		 AverageReturn = -126110.0
		 AverageEpisodeLength = 14.0


Iteration:  26000
Replay buffer len: 99526


INFO:absl: 
		 NumberOfEpisodes = 3940
		 EnvironmentSteps = 54002
		 AverageReturn = -129008.0
		 AverageEpisodeLength = 12.699999809265137


Iteration:  27000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 4063
		 EnvironmentSteps = 56002
		 AverageReturn = -132213.5
		 AverageEpisodeLength = 13.800000190734863


Iteration:  28000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 4178
		 EnvironmentSteps = 58002
		 AverageReturn = -135163.0
		 AverageEpisodeLength = 21.200000762939453


Iteration:  29000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 4297
		 EnvironmentSteps = 60002
		 AverageReturn = -138133.5
		 AverageEpisodeLength = 23.200000762939453


Iteration:  30000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 4403
		 EnvironmentSteps = 62002
		 AverageReturn = -140598.5
		 AverageEpisodeLength = 20.399999618530273


Iteration:  31000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 4513
		 EnvironmentSteps = 64002
		 AverageReturn = -143220.0
		 AverageEpisodeLength = 16.899999618530273


Iteration:  32000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 4621
		 EnvironmentSteps = 66002
		 AverageReturn = -145796.0
		 AverageEpisodeLength = 17.799999237060547


Iteration:  33000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 4720
		 EnvironmentSteps = 68002
		 AverageReturn = -147999.5
		 AverageEpisodeLength = 17.299999237060547


Iteration:  34000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 4821
		 EnvironmentSteps = 70002
		 AverageReturn = -150332.0
		 AverageEpisodeLength = 23.799999237060547


Iteration:  35000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 4922
		 EnvironmentSteps = 72002
		 AverageReturn = -152412.0
		 AverageEpisodeLength = 7.0


Iteration:  36000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 5023
		 EnvironmentSteps = 74002
		 AverageReturn = -154734.0
		 AverageEpisodeLength = 22.399999618530273


Iteration:  37000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 5140
		 EnvironmentSteps = 76002
		 AverageReturn = -157640.0
		 AverageEpisodeLength = 17.700000762939453


Iteration:  38000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 5233
		 EnvironmentSteps = 78002
		 AverageReturn = -159542.5
		 AverageEpisodeLength = 14.699999809265137


Iteration:  39000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 5349
		 EnvironmentSteps = 80002
		 AverageReturn = -162319.0
		 AverageEpisodeLength = 13.399999618530273


Iteration:  40000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 5446
		 EnvironmentSteps = 82002
		 AverageReturn = -164374.5
		 AverageEpisodeLength = 10.5


Iteration:  41000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 5543
		 EnvironmentSteps = 84002
		 AverageReturn = -166585.0
		 AverageEpisodeLength = 17.299999237060547


Iteration:  42000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 5653
		 EnvironmentSteps = 86002
		 AverageReturn = -169351.5
		 AverageEpisodeLength = 13.199999809265137


Iteration:  43000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 5756
		 EnvironmentSteps = 88002
		 AverageReturn = -171437.0
		 AverageEpisodeLength = 9.699999809265137


Iteration:  44000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 5856
		 EnvironmentSteps = 90002
		 AverageReturn = -173703.5
		 AverageEpisodeLength = 14.800000190734863


Iteration:  45000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 5947
		 EnvironmentSteps = 92002
		 AverageReturn = -175370.5
		 AverageEpisodeLength = 29.799999237060547


Iteration:  46000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 6046
		 EnvironmentSteps = 94002
		 AverageReturn = -177537.5
		 AverageEpisodeLength = 13.300000190734863


Iteration:  47000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 6134
		 EnvironmentSteps = 96002
		 AverageReturn = -179148.5
		 AverageEpisodeLength = 26.600000381469727


Iteration:  48000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 6232
		 EnvironmentSteps = 98002
		 AverageReturn = -181274.0
		 AverageEpisodeLength = 25.799999237060547


Iteration:  49000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 6350
		 EnvironmentSteps = 100002
		 AverageReturn = -184096.5
		 AverageEpisodeLength = 11.699999809265137


Iteration:  50000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 6435
		 EnvironmentSteps = 102002
		 AverageReturn = -185754.0
		 AverageEpisodeLength = 18.799999237060547


Iteration:  51000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 6528
		 EnvironmentSteps = 104002
		 AverageReturn = -187891.5
		 AverageEpisodeLength = 33.5


Iteration:  52000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 6617
		 EnvironmentSteps = 106002
		 AverageReturn = -189499.0
		 AverageEpisodeLength = 21.5


Iteration:  53000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 6715
		 EnvironmentSteps = 108002
		 AverageReturn = -191576.5
		 AverageEpisodeLength = 17.799999237060547


Iteration:  54000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 6799
		 EnvironmentSteps = 110002
		 AverageReturn = -193198.5
		 AverageEpisodeLength = 30.600000381469727


Iteration:  55000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 6888
		 EnvironmentSteps = 112002
		 AverageReturn = -194765.5
		 AverageEpisodeLength = 31.0


Iteration:  56000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 6970
		 EnvironmentSteps = 114002
		 AverageReturn = -196250.5
		 AverageEpisodeLength = 21.100000381469727


Iteration:  57000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 7044
		 EnvironmentSteps = 116002
		 AverageReturn = -197400.5
		 AverageEpisodeLength = 21.299999237060547


Iteration:  58000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 7111
		 EnvironmentSteps = 118002
		 AverageReturn = -198247.0
		 AverageEpisodeLength = 23.299999237060547


Iteration:  59000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 7197
		 EnvironmentSteps = 120002
		 AverageReturn = -199737.0
		 AverageEpisodeLength = 11.199999809265137


Iteration:  60000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 7272
		 EnvironmentSteps = 122002
		 AverageReturn = -200964.0
		 AverageEpisodeLength = 27.5


Iteration:  61000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 7352
		 EnvironmentSteps = 124002
		 AverageReturn = -202363.5
		 AverageEpisodeLength = 25.299999237060547


Iteration:  62000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 7423
		 EnvironmentSteps = 126002
		 AverageReturn = -203331.0
		 AverageEpisodeLength = 22.399999618530273


Iteration:  63000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 7498
		 EnvironmentSteps = 128002
		 AverageReturn = -204539.0
		 AverageEpisodeLength = 25.0


Iteration:  64000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 7571
		 EnvironmentSteps = 130002
		 AverageReturn = -205717.0
		 AverageEpisodeLength = 28.399999618530273


Iteration:  65000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 7642
		 EnvironmentSteps = 132002
		 AverageReturn = -206701.0
		 AverageEpisodeLength = 25.200000762939453


Iteration:  66000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 7717
		 EnvironmentSteps = 134002
		 AverageReturn = -207780.5
		 AverageEpisodeLength = 19.399999618530273


Iteration:  67000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 7788
		 EnvironmentSteps = 136002
		 AverageReturn = -208835.0
		 AverageEpisodeLength = 18.799999237060547


Iteration:  68000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 7877
		 EnvironmentSteps = 138002
		 AverageReturn = -210456.0
		 AverageEpisodeLength = 14.0


Iteration:  69000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 7947
		 EnvironmentSteps = 140002
		 AverageReturn = -211443.5
		 AverageEpisodeLength = 29.399999618530273


Iteration:  70000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 8019
		 EnvironmentSteps = 142002
		 AverageReturn = -212483.5
		 AverageEpisodeLength = 21.899999618530273


Iteration:  71000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 8092
		 EnvironmentSteps = 144002
		 AverageReturn = -213603.0
		 AverageEpisodeLength = 21.600000381469727


Iteration:  72000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 8162
		 EnvironmentSteps = 146002
		 AverageReturn = -214562.0
		 AverageEpisodeLength = 41.20000076293945


Iteration:  73000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 8239
		 EnvironmentSteps = 148002
		 AverageReturn = -215693.0
		 AverageEpisodeLength = 30.399999618530273


Iteration:  74000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 8317
		 EnvironmentSteps = 150002
		 AverageReturn = -216797.5
		 AverageEpisodeLength = 18.0


Iteration:  75000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 8383
		 EnvironmentSteps = 152002
		 AverageReturn = -217549.0
		 AverageEpisodeLength = 26.200000762939453


Iteration:  76000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 8456
		 EnvironmentSteps = 154002
		 AverageReturn = -218534.0
		 AverageEpisodeLength = 26.0


Iteration:  77000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 8522
		 EnvironmentSteps = 156002
		 AverageReturn = -219422.0
		 AverageEpisodeLength = 43.900001525878906


Iteration:  78000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 8589
		 EnvironmentSteps = 158002
		 AverageReturn = -220169.0
		 AverageEpisodeLength = 21.899999618530273


Iteration:  79000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 8664
		 EnvironmentSteps = 160002
		 AverageReturn = -221181.5
		 AverageEpisodeLength = 22.200000762939453


Iteration:  80000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 8733
		 EnvironmentSteps = 162002
		 AverageReturn = -221944.5
		 AverageEpisodeLength = 17.399999618530273


Iteration:  81000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 8795
		 EnvironmentSteps = 164002
		 AverageReturn = -222629.5
		 AverageEpisodeLength = 40.099998474121094


Iteration:  82000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 8854
		 EnvironmentSteps = 166002
		 AverageReturn = -222811.5
		 AverageEpisodeLength = 16.5


Iteration:  83000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 8916
		 EnvironmentSteps = 168002
		 AverageReturn = -223471.5
		 AverageEpisodeLength = 24.799999237060547


Iteration:  84000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 8985
		 EnvironmentSteps = 170002
		 AverageReturn = -224138.0
		 AverageEpisodeLength = 19.299999237060547


Iteration:  85000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 9039
		 EnvironmentSteps = 172002
		 AverageReturn = -224480.0
		 AverageEpisodeLength = 29.100000381469727


Iteration:  86000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 9102
		 EnvironmentSteps = 174002
		 AverageReturn = -225135.5
		 AverageEpisodeLength = 33.900001525878906


Iteration:  87000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 9162
		 EnvironmentSteps = 176002
		 AverageReturn = -225460.5
		 AverageEpisodeLength = 16.100000381469727


Iteration:  88000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 9217
		 EnvironmentSteps = 178002
		 AverageReturn = -225939.0
		 AverageEpisodeLength = 26.700000762939453


Iteration:  89000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 9281
		 EnvironmentSteps = 180002
		 AverageReturn = -226727.0
		 AverageEpisodeLength = 41.900001525878906


Iteration:  90000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 9343
		 EnvironmentSteps = 182002
		 AverageReturn = -227212.5
		 AverageEpisodeLength = 31.0


Iteration:  91000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 9405
		 EnvironmentSteps = 184002
		 AverageReturn = -227637.5
		 AverageEpisodeLength = 29.600000381469727


Iteration:  92000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 9451
		 EnvironmentSteps = 186002
		 AverageReturn = -227636.5
		 AverageEpisodeLength = 32.79999923706055


Iteration:  93000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 9506
		 EnvironmentSteps = 188002
		 AverageReturn = -227934.5
		 AverageEpisodeLength = 41.0


Iteration:  94000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 9553
		 EnvironmentSteps = 190002
		 AverageReturn = -227878.5
		 AverageEpisodeLength = 40.099998474121094


Iteration:  95000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 9609
		 EnvironmentSteps = 192002
		 AverageReturn = -228057.5
		 AverageEpisodeLength = 26.399999618530273


Iteration:  96000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 9662
		 EnvironmentSteps = 194002
		 AverageReturn = -228149.5
		 AverageEpisodeLength = 29.399999618530273


Iteration:  97000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 9718
		 EnvironmentSteps = 196002
		 AverageReturn = -228432.0
		 AverageEpisodeLength = 39.20000076293945


Iteration:  98000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 9770
		 EnvironmentSteps = 198002
		 AverageReturn = -228383.0
		 AverageEpisodeLength = 41.099998474121094


Iteration:  99000
Replay buffer len: 100000


In [24]:
# Evaluate the agent

test_scene = Scene(init_randomly=True)
test_env = SnakeGame(test_scene)
test_env = TFPyEnvironment(test_env)

time_step = test_env.reset()
rewards = []
steps = 0

while not time_step.is_last() and steps < 200:
    steps += 1
    print("Map:\n", np.argmax(time_step.observation[0], axis=3))
    print("Direction:\n", time_step.observation[1])
    print("No body blocks:\n", time_step.observation[2])
    action_step = agent.policy.action(time_step)
    print("Action: ", action_step.action.numpy())
    time_step = test_env.step(action_step.action)
    rewards.append(time_step.reward.numpy()[0])
    
print("Total reward: ", sum(rewards))
print("Total steps: ", steps)


Map:
 [[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 3 0 0 0]
  [0 0 0 0 0]
  [1 2 0 0 0]]]
Direction:
 tf.Tensor([[ True False  True  True]], shape=(1, 4), dtype=bool)
No body blocks:
 tf.Tensor([[0.  0.5 0.5 0. ]], shape=(1, 4), dtype=float32)
Action:  [1]
Map:
 [[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 3 0 0 0]
  [1 0 0 0 0]
  [2 0 0 0 0]]]
Direction:
 tf.Tensor([[ True False False  True]], shape=(1, 4), dtype=bool)
No body blocks:
 tf.Tensor([[0.    0.375 0.5   0.125]], shape=(1, 4), dtype=float32)
Action:  [2]
Map:
 [[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 3 0 0 0]
  [2 1 0 0 0]
  [0 0 0 0 0]]]
Direction:
 tf.Tensor([[ True False False False]], shape=(1, 4), dtype=bool)
No body blocks:
 tf.Tensor([[0.125 0.375 0.375 0.125]], shape=(1, 4), dtype=float32)
Action:  [1]
Map:
 [[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 1 0 0 0]
  [2 2 0 0 0]
  [0 0 3 0 0]]]
Direction:
 tf.Tensor([[False False False  True]], shape=(1, 4), dtype=bool)
No body blocks:
 tf.Tensor([[0.12820514 0.25641027 0.3846154  0.23076923]], shape=(1, 4), dtyp

In [25]:

# Count the average steps per episode

n = 500
total_steps = 0
total_reward = 0
steps = 0
total_500 = 0
wins = 0

for i in range(n):
    if i % 10 == 0 and i != 0:
        print("Episode: ", i)
        
    time_step = test_env.reset()
    steps = 0
    episode_reward = 0
    while not time_step.is_last() and steps < 500:
        steps += 1
        action_step = agent.policy.action(time_step)
        time_step = test_env.step(action_step.action)
        reward = time_step.reward.numpy()[0]
        total_reward += reward
        episode_reward += reward
        
    if episode_reward == 115:
        wins += 1
    
    if steps == 500:
        total_500 += 1
    else:
        total_steps += steps
        
    if i % 10 == 0 and i != 0:
        print("Avg reward: ", total_reward / (i + 1))
        
if steps == 500:
    print("500 episodes reached")
    
print("Average steps per episode: ", total_steps / (n - total_500))
print("Average reward per episode: ", total_reward / n)
print("Total 500 episodes: ", total_500)
print("Wins: ", wins)


Episode:  10
Avg reward:  44.09090909090909
Episode:  20
Avg reward:  38.095238095238095
Episode:  30
Avg reward:  39.03225806451613
Episode:  40
Avg reward:  42.19512195121951
Episode:  50
Avg reward:  41.76470588235294
Episode:  60
Avg reward:  41.721311475409834
Episode:  70
Avg reward:  43.66197183098591
Episode:  80
Avg reward:  44.44444444444444
Episode:  90
Avg reward:  44.010989010989015
Episode:  100
Avg reward:  44.20792079207921
Episode:  110
Avg reward:  45.04504504504504
Episode:  120
Avg reward:  44.79338842975206
Episode:  130
Avg reward:  45.725190839694655
Episode:  140
Avg reward:  44.57446808510638
Episode:  150
Avg reward:  45.2317880794702
Episode:  160
Avg reward:  45.43478260869565
Episode:  170
Avg reward:  45.84795321637427
Episode:  180
Avg reward:  46.43646408839779
Episode:  190
Avg reward:  46.49214659685864
Episode:  200
Avg reward:  47.08955223880597
Episode:  210
Avg reward:  47.03791469194313
Episode:  220
Avg reward:  47.23981900452489
Episode:  230
Av

In [26]:
# Save the q network weights
tf.keras.models.save_model(q_net._model, "q_network_x.h5")

/var/folders/bw/_7s8wxw93cngpt5f7bg5s3hm0000gn/T/ipykernel_28307/4087533747.py:2: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  tf.keras.models.save_model(q_net._model, "q_network_5x5_3.h5")
