In [30]:
import numpy as np
import tensorflow as tf
from tf_agents.networks.q_network import QNetwork
import tf_agents.networks.network as network
from tf_agents.specs import tensor_spec
from snake_game import SnakeGame
from scene import Scene
from scene_longer_snake import SceneLongerSnake
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Flatten, Conv2D, Input

scene = SceneLongerSnake(init_randomly=True, snake_longer_prob=0.95, length_mean=10, length_std=2)
episodes_count = 80000
random_episodes = 20000


In [31]:
from tf_agents.environments.tf_py_environment import TFPyEnvironment

env = SnakeGame(scene)
env = TFPyEnvironment(env)


In [32]:
class MyQNetwork(network.Network):
    def __init__(self,
                 input_tensor_spec,
                 action_spec,
                 name='MyQNetwork'):
        super(MyQNetwork, self).__init__(
            input_tensor_spec=input_tensor_spec,
            state_spec=(),
            name=name)
        
        self._action_spec = action_spec
        matrix_shape = input_tensor_spec[0].shape
        obstacles_shape = input_tensor_spec[1].shape
        no_body_blocks_shape = input_tensor_spec[2].shape
        
        input0 = Input(shape=matrix_shape)
        input1 = Input(shape=obstacles_shape) # Each value represents if there is a wall or the snake body in the direction, 0 - no wall, 1 - wall
        input2 = Input(shape=no_body_blocks_shape) # Each value represents how many no body blocks are in the direction
        
        conv = Conv2D(32, (2, 2), 1, activation='relu', kernel_initializer='he_normal')(input0)
        flat = Flatten()(conv)
        dense1 = Dense(128, activation='relu', kernel_initializer='he_normal')(flat)
        dense2 = Dense(32, activation='relu', kernel_initializer='he_normal')(dense1)
        
        concat = tf.keras.layers.concatenate([dense2, input1, input2])
        output = Dense(4, activation='linear')(concat)
        
        self._model = tf.keras.Model(inputs=[input0, input1, input2], outputs=output)
        
        self._model.summary()

    def call(self, observations, step_type=None, network_state=(), training=False):
        output = self._model([observations[0], observations[1], observations[2]])
        return output, network_state

q_net = MyQNetwork(
    env.observation_spec(),
    env.action_spec())


Model: "model_4"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_20 (InputLayer)       [(None, 5, 5, 4)]            0         []                            
                                                                                                  
 conv2d_5 (Conv2D)           (None, 4, 4, 32)             544       ['input_20[0][0]']            
                                                                                                  
 flatten_5 (Flatten)         (None, 512)                  0         ['conv2d_5[0][0]']            


                                                                                                  
 dense_15 (Dense)            (None, 128)                  65664     ['flatten_5[0][0]']           
                                                                                                  
 dense_16 (Dense)            (None, 32)                   4128      ['dense_15[0][0]']            
                                                                                                  
 input_21 (InputLayer)       [(None, 4)]                  0         []                            
                                                                                                  
 input_22 (InputLayer)       [(None, 4)]                  0         []                            
                                                                                                  
 concatenate_5 (Concatenate  (None, 40)                   0         ['dense_16[0][0]',            
 )        

In [33]:
# Create the agent
from tf_agents.agents.dqn.dqn_agent import DdqnAgent
from tensorflow import keras
from keras.optimizers.legacy import Adam
from keras.losses import Huber
from tf_agents.trajectories import TimeStep

train_step_counter = tf.Variable(0)
optimizer = Adam(learning_rate=0.003)

epsilon = keras.optimizers.schedules.PolynomialDecay(
    initial_learning_rate=0.1,
    decay_steps=episodes_count,
    end_learning_rate=0.01
)

agent = DdqnAgent(
    time_step_spec=env.time_step_spec(),
    action_spec=env.action_spec(),
    q_network=q_net,
    optimizer=optimizer,
    td_errors_loss_fn=Huber(reduction="none"),
    gamma=tf.constant(0.95, dtype=tf.float32),
    train_step_counter=train_step_counter,
    epsilon_greedy=lambda: epsilon(train_step_counter)
)


Model: "model_5"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_23 (InputLayer)       [(None, 5, 5, 4)]            0         []                            
                                                                                                  
 conv2d_6 (Conv2D)           (None, 4, 4, 32)             544       ['input_23[0][0]']            
                                                                                                  
 flatten_6 (Flatten)         (None, 512)                  0         ['conv2d_6[0][0]']            
                                                                                                  
 dense_18 (Dense)            (None, 128)                  65664     ['flatten_6[0][0]']           
                                                                                            

In [34]:
# Create the replay buffer
from tf_agents.replay_buffers import tf_uniform_replay_buffer

replay_buffer = tf_uniform_replay_buffer.TFUniformReplayBuffer(
    data_spec=agent.collect_data_spec,
    batch_size=env.batch_size,
    max_length=100000
)


In [35]:
# Create the training metrics
from tf_agents.metrics import tf_metrics

train_metrics = [
    tf_metrics.NumberOfEpisodes(),
    tf_metrics.EnvironmentSteps(),
    tf_metrics.AverageReturnMetric(),
    tf_metrics.AverageEpisodeLengthMetric()
]


In [36]:
# Create the driver
from tf_agents.drivers import dynamic_step_driver

collect_driver = dynamic_step_driver.DynamicStepDriver(
    env,
    policy=agent.collect_policy,
    observers=[replay_buffer.add_batch] + train_metrics,
    num_steps=2
)

# Run a random policy to fill the replay buffer
from tf_agents.policies.random_tf_policy import RandomTFPolicy

initial_collect_policy = RandomTFPolicy(env.time_step_spec(), env.action_spec())
init_driver = dynamic_step_driver.DynamicStepDriver(
    env,
    policy=initial_collect_policy,
    observers=[replay_buffer.add_batch],
    num_steps=random_episodes
)

final_time_step, final_policy_state = init_driver.run()


In [37]:
# Create the dataset
dataset = replay_buffer.as_dataset(
    sample_batch_size=64,
    num_steps=2, # Capaz cambiar esto
    num_parallel_calls=5
).prefetch(5)


In [38]:

# Create the training loop

from tf_agents.utils.common import function
from tf_agents.trajectories import trajectory
from tf_agents.eval.metric_utils import log_metrics
import logging

logging.getLogger().setLevel(logging.INFO)

collect_driver.run = function(collect_driver.run)
agent.train = function(agent.train)

def train_agent(n_iterations):
    time_step = None
    policy_state = agent.collect_policy.get_initial_state(env.batch_size)
    iterator = iter(dataset)
    for iteration in range(n_iterations):
        time_step, policy_state = collect_driver.run(time_step, policy_state)
        trajectories, buffer_info = next(iterator)
        train_loss = agent.train(trajectories)
        if iteration % 1000 == 0:
            print("Iteration: ", iteration)
            print("Replay buffer len: " + str(replay_buffer.num_frames().numpy()))
            log_metrics(train_metrics)


In [39]:
train_agent(episodes_count)


INFO:absl: 
		 NumberOfEpisodes = 0
		 EnvironmentSteps = 2
		 AverageReturn = 0.0
		 AverageEpisodeLength = 0.0


Iteration:  0
Replay buffer len: 43583


INFO:absl: 
		 NumberOfEpisodes = 255
		 EnvironmentSteps = 2002
		 AverageReturn = -9579.0
		 AverageEpisodeLength = 18.600000381469727


Iteration:  1000
Replay buffer len: 45838


INFO:absl: 
		 NumberOfEpisodes = 408
		 EnvironmentSteps = 4002
		 AverageReturn = -14873.5
		 AverageEpisodeLength = 15.899999618530273


Iteration:  2000
Replay buffer len: 47991


INFO:absl: 
		 NumberOfEpisodes = 560
		 EnvironmentSteps = 6002
		 AverageReturn = -19894.5
		 AverageEpisodeLength = 18.100000381469727


Iteration:  3000
Replay buffer len: 50143


INFO:absl: 
		 NumberOfEpisodes = 677
		 EnvironmentSteps = 8002
		 AverageReturn = -23271.5
		 AverageEpisodeLength = 13.600000381469727


Iteration:  4000
Replay buffer len: 52260


INFO:absl: 
		 NumberOfEpisodes = 803
		 EnvironmentSteps = 10002
		 AverageReturn = -27122.0
		 AverageEpisodeLength = 16.600000381469727


Iteration:  5000
Replay buffer len: 54386


INFO:absl: 
		 NumberOfEpisodes = 926
		 EnvironmentSteps = 12002
		 AverageReturn = -30649.5
		 AverageEpisodeLength = 17.799999237060547


Iteration:  6000
Replay buffer len: 56509


INFO:absl: 
		 NumberOfEpisodes = 1074
		 EnvironmentSteps = 14002
		 AverageReturn = -35117.5
		 AverageEpisodeLength = 17.5


Iteration:  7000
Replay buffer len: 58657


INFO:absl: 
		 NumberOfEpisodes = 1195
		 EnvironmentSteps = 16002
		 AverageReturn = -38372.0
		 AverageEpisodeLength = 14.899999618530273


Iteration:  8000
Replay buffer len: 60778


INFO:absl: 
		 NumberOfEpisodes = 1341
		 EnvironmentSteps = 18002
		 AverageReturn = -42714.0
		 AverageEpisodeLength = 11.199999809265137


Iteration:  9000
Replay buffer len: 62924


INFO:absl: 
		 NumberOfEpisodes = 1466
		 EnvironmentSteps = 20002
		 AverageReturn = -46130.0
		 AverageEpisodeLength = 5.900000095367432


Iteration:  10000
Replay buffer len: 65049


INFO:absl: 
		 NumberOfEpisodes = 1593
		 EnvironmentSteps = 22002
		 AverageReturn = -49639.0
		 AverageEpisodeLength = 18.299999237060547


Iteration:  11000
Replay buffer len: 67176


INFO:absl: 
		 NumberOfEpisodes = 1709
		 EnvironmentSteps = 24002
		 AverageReturn = -52639.0
		 AverageEpisodeLength = 20.299999237060547


Iteration:  12000
Replay buffer len: 69292


INFO:absl: 
		 NumberOfEpisodes = 1829
		 EnvironmentSteps = 26002
		 AverageReturn = -55677.0
		 AverageEpisodeLength = 20.399999618530273


Iteration:  13000
Replay buffer len: 71412


INFO:absl: 
		 NumberOfEpisodes = 1946
		 EnvironmentSteps = 28002
		 AverageReturn = -58520.0
		 AverageEpisodeLength = 10.800000190734863


Iteration:  14000
Replay buffer len: 73529


INFO:absl: 
		 NumberOfEpisodes = 2078
		 EnvironmentSteps = 30002
		 AverageReturn = -62175.0
		 AverageEpisodeLength = 14.0


Iteration:  15000
Replay buffer len: 75661


INFO:absl: 
		 NumberOfEpisodes = 2211
		 EnvironmentSteps = 32002
		 AverageReturn = -65717.0
		 AverageEpisodeLength = 19.5


Iteration:  16000
Replay buffer len: 77794


INFO:absl: 
		 NumberOfEpisodes = 2331
		 EnvironmentSteps = 34002
		 AverageReturn = -68824.5
		 AverageEpisodeLength = 16.899999618530273


Iteration:  17000
Replay buffer len: 79914


INFO:absl: 
		 NumberOfEpisodes = 2449
		 EnvironmentSteps = 36002
		 AverageReturn = -71625.5
		 AverageEpisodeLength = 23.299999237060547


Iteration:  18000
Replay buffer len: 82032


INFO:absl: 
		 NumberOfEpisodes = 2560
		 EnvironmentSteps = 38002
		 AverageReturn = -74187.5
		 AverageEpisodeLength = 17.600000381469727


Iteration:  19000
Replay buffer len: 84143


INFO:absl: 
		 NumberOfEpisodes = 2657
		 EnvironmentSteps = 40002
		 AverageReturn = -76421.0
		 AverageEpisodeLength = 15.800000190734863


Iteration:  20000
Replay buffer len: 86240


INFO:absl: 
		 NumberOfEpisodes = 2786
		 EnvironmentSteps = 42002
		 AverageReturn = -79731.0
		 AverageEpisodeLength = 13.0


Iteration:  21000
Replay buffer len: 88369


INFO:absl: 
		 NumberOfEpisodes = 2903
		 EnvironmentSteps = 44002
		 AverageReturn = -82609.5
		 AverageEpisodeLength = 19.399999618530273


Iteration:  22000
Replay buffer len: 90486


INFO:absl: 
		 NumberOfEpisodes = 3012
		 EnvironmentSteps = 46002
		 AverageReturn = -85265.5
		 AverageEpisodeLength = 14.899999618530273


Iteration:  23000
Replay buffer len: 92595


INFO:absl: 
		 NumberOfEpisodes = 3118
		 EnvironmentSteps = 48002
		 AverageReturn = -87621.0
		 AverageEpisodeLength = 19.0


Iteration:  24000
Replay buffer len: 94701


INFO:absl: 
		 NumberOfEpisodes = 3237
		 EnvironmentSteps = 50002
		 AverageReturn = -90420.0
		 AverageEpisodeLength = 7.099999904632568


Iteration:  25000
Replay buffer len: 96820


INFO:absl: 
		 NumberOfEpisodes = 3349
		 EnvironmentSteps = 52002
		 AverageReturn = -93040.5
		 AverageEpisodeLength = 25.700000762939453


Iteration:  26000
Replay buffer len: 98932


INFO:absl: 
		 NumberOfEpisodes = 3453
		 EnvironmentSteps = 54002
		 AverageReturn = -95169.5
		 AverageEpisodeLength = 25.700000762939453


Iteration:  27000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 3565
		 EnvironmentSteps = 56002
		 AverageReturn = -97739.0
		 AverageEpisodeLength = 15.199999809265137


Iteration:  28000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 3670
		 EnvironmentSteps = 58002
		 AverageReturn = -100173.0
		 AverageEpisodeLength = 19.299999237060547


Iteration:  29000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 3771
		 EnvironmentSteps = 60002
		 AverageReturn = -102412.5
		 AverageEpisodeLength = 25.100000381469727


Iteration:  30000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 3873
		 EnvironmentSteps = 62002
		 AverageReturn = -104793.0
		 AverageEpisodeLength = 24.899999618530273


Iteration:  31000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 3960
		 EnvironmentSteps = 64002
		 AverageReturn = -106428.0
		 AverageEpisodeLength = 17.700000762939453


Iteration:  32000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 4059
		 EnvironmentSteps = 66002
		 AverageReturn = -108533.0
		 AverageEpisodeLength = 18.100000381469727


Iteration:  33000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 4171
		 EnvironmentSteps = 68002
		 AverageReturn = -111291.0
		 AverageEpisodeLength = 15.800000190734863


Iteration:  34000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 4268
		 EnvironmentSteps = 70002
		 AverageReturn = -113454.5
		 AverageEpisodeLength = 29.799999237060547


Iteration:  35000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 4363
		 EnvironmentSteps = 72002
		 AverageReturn = -115388.5
		 AverageEpisodeLength = 19.299999237060547


Iteration:  36000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 4468
		 EnvironmentSteps = 74002
		 AverageReturn = -117813.5
		 AverageEpisodeLength = 14.300000190734863


Iteration:  37000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 4570
		 EnvironmentSteps = 76002
		 AverageReturn = -119977.5
		 AverageEpisodeLength = 18.5


Iteration:  38000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 4662
		 EnvironmentSteps = 78002
		 AverageReturn = -121998.5
		 AverageEpisodeLength = 33.20000076293945


Iteration:  39000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 4752
		 EnvironmentSteps = 80002
		 AverageReturn = -123714.5
		 AverageEpisodeLength = 22.200000762939453


Iteration:  40000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 4830
		 EnvironmentSteps = 82002
		 AverageReturn = -124978.5
		 AverageEpisodeLength = 26.200000762939453


Iteration:  41000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 4915
		 EnvironmentSteps = 84002
		 AverageReturn = -126599.0
		 AverageEpisodeLength = 19.299999237060547


Iteration:  42000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 5004
		 EnvironmentSteps = 86002
		 AverageReturn = -128208.5
		 AverageEpisodeLength = 22.799999237060547


Iteration:  43000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 5077
		 EnvironmentSteps = 88002
		 AverageReturn = -129385.5
		 AverageEpisodeLength = 32.79999923706055


Iteration:  44000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 5166
		 EnvironmentSteps = 90002
		 AverageReturn = -130914.0
		 AverageEpisodeLength = 14.399999618530273


Iteration:  45000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 5245
		 EnvironmentSteps = 92002
		 AverageReturn = -132261.0
		 AverageEpisodeLength = 24.799999237060547


Iteration:  46000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 5338
		 EnvironmentSteps = 94002
		 AverageReturn = -134085.0
		 AverageEpisodeLength = 20.700000762939453


Iteration:  47000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 5429
		 EnvironmentSteps = 96002
		 AverageReturn = -135812.0
		 AverageEpisodeLength = 23.799999237060547


Iteration:  48000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 5502
		 EnvironmentSteps = 98002
		 AverageReturn = -136828.0
		 AverageEpisodeLength = 20.399999618530273


Iteration:  49000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 5591
		 EnvironmentSteps = 100002
		 AverageReturn = -138438.5
		 AverageEpisodeLength = 29.200000762939453


Iteration:  50000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 5674
		 EnvironmentSteps = 102002
		 AverageReturn = -139940.5
		 AverageEpisodeLength = 33.0


Iteration:  51000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 5755
		 EnvironmentSteps = 104002
		 AverageReturn = -141241.0
		 AverageEpisodeLength = 26.299999237060547


Iteration:  52000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 5840
		 EnvironmentSteps = 106002
		 AverageReturn = -142713.5
		 AverageEpisodeLength = 20.100000381469727


Iteration:  53000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 5933
		 EnvironmentSteps = 108002
		 AverageReturn = -144418.5
		 AverageEpisodeLength = 32.79999923706055


Iteration:  54000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 6013
		 EnvironmentSteps = 110002
		 AverageReturn = -145575.5
		 AverageEpisodeLength = 35.099998474121094


Iteration:  55000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 6080
		 EnvironmentSteps = 112002
		 AverageReturn = -146148.0
		 AverageEpisodeLength = 13.699999809265137


Iteration:  56000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 6156
		 EnvironmentSteps = 114002
		 AverageReturn = -147188.0
		 AverageEpisodeLength = 23.200000762939453


Iteration:  57000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 6221
		 EnvironmentSteps = 116002
		 AverageReturn = -147746.5
		 AverageEpisodeLength = 34.20000076293945


Iteration:  58000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 6307
		 EnvironmentSteps = 118002
		 AverageReturn = -149132.5
		 AverageEpisodeLength = 29.200000762939453


Iteration:  59000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 6388
		 EnvironmentSteps = 120002
		 AverageReturn = -150397.5
		 AverageEpisodeLength = 18.0


Iteration:  60000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 6453
		 EnvironmentSteps = 122002
		 AverageReturn = -151061.0
		 AverageEpisodeLength = 36.599998474121094


Iteration:  61000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 6518
		 EnvironmentSteps = 124002
		 AverageReturn = -151641.5
		 AverageEpisodeLength = 27.799999237060547


Iteration:  62000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 6577
		 EnvironmentSteps = 126002
		 AverageReturn = -152020.0
		 AverageEpisodeLength = 31.399999618530273


Iteration:  63000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 6635
		 EnvironmentSteps = 128002
		 AverageReturn = -152377.0
		 AverageEpisodeLength = 33.70000076293945


Iteration:  64000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 6710
		 EnvironmentSteps = 130002
		 AverageReturn = -153478.0
		 AverageEpisodeLength = 27.600000381469727


Iteration:  65000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 6787
		 EnvironmentSteps = 132002
		 AverageReturn = -154588.0
		 AverageEpisodeLength = 17.600000381469727


Iteration:  66000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 6858
		 EnvironmentSteps = 134002
		 AverageReturn = -155292.0
		 AverageEpisodeLength = 28.200000762939453


Iteration:  67000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 6932
		 EnvironmentSteps = 136002
		 AverageReturn = -156194.0
		 AverageEpisodeLength = 31.799999237060547


Iteration:  68000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 6993
		 EnvironmentSteps = 138002
		 AverageReturn = -156626.0
		 AverageEpisodeLength = 30.5


Iteration:  69000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 7058
		 EnvironmentSteps = 140002
		 AverageReturn = -157199.5
		 AverageEpisodeLength = 28.5


Iteration:  70000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 7119
		 EnvironmentSteps = 142002
		 AverageReturn = -157674.5
		 AverageEpisodeLength = 33.20000076293945


Iteration:  71000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 7179
		 EnvironmentSteps = 144002
		 AverageReturn = -157931.5
		 AverageEpisodeLength = 36.599998474121094


Iteration:  72000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 7250
		 EnvironmentSteps = 146002
		 AverageReturn = -158619.5
		 AverageEpisodeLength = 26.299999237060547


Iteration:  73000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 7311
		 EnvironmentSteps = 148002
		 AverageReturn = -159017.5
		 AverageEpisodeLength = 33.599998474121094


Iteration:  74000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 7359
		 EnvironmentSteps = 150002
		 AverageReturn = -158996.5
		 AverageEpisodeLength = 41.099998474121094


Iteration:  75000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 7424
		 EnvironmentSteps = 152002
		 AverageReturn = -159598.5
		 AverageEpisodeLength = 34.79999923706055


Iteration:  76000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 7480
		 EnvironmentSteps = 154002
		 AverageReturn = -159830.5
		 AverageEpisodeLength = 26.5


Iteration:  77000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 7530
		 EnvironmentSteps = 156002
		 AverageReturn = -159941.5
		 AverageEpisodeLength = 37.70000076293945


Iteration:  78000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 7577
		 EnvironmentSteps = 158002
		 AverageReturn = -159753.5
		 AverageEpisodeLength = 30.399999618530273


Iteration:  79000
Replay buffer len: 100000


In [40]:
# Evaluate the agent

test_scene = Scene(init_randomly=True)
test_env = SnakeGame(test_scene)
test_env = TFPyEnvironment(test_env)

time_step = test_env.reset()
rewards = []
steps = 0

while not time_step.is_last() and steps < 200:
    steps += 1
    print("Map:\n", np.argmax(time_step.observation[0], axis=3))
    print("Direction:\n", time_step.observation[1])
    print("No body blocks:\n", time_step.observation[4])
    action_step = agent.policy.action(time_step)
    print("Action: ", action_step.action.numpy())
    time_step = test_env.step(action_step.action)
    rewards.append(time_step.reward.numpy()[0])
    
print("Total reward: ", sum(rewards))
print("Total steps: ", steps)


Map:
 [[[3 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 1]
  [0 0 0 0 2]]]
Direction:
 tf.Tensor([[False False  True  True]], shape=(1, 4), dtype=bool)
No body blocks:
 tf.Tensor([[20 15  0  4]], shape=(1, 4), dtype=uint8)
Action:  [0]
Map:
 [[[3 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 1 2]
  [0 0 0 0 0]]]
Direction:
 tf.Tensor([[False False  True False]], shape=(1, 4), dtype=bool)
No body blocks:
 tf.Tensor([[15 15  4  5]], shape=(1, 4), dtype=uint8)
Action:  [1]
Map:
 [[[3 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 1 0]
  [0 0 0 2 0]
  [0 0 0 0 0]]]
Direction:
 tf.Tensor([[False False False  True]], shape=(1, 4), dtype=bool)
No body blocks:
 tf.Tensor([[15 10  5  9]], shape=(1, 4), dtype=uint8)
Action:  [1]
Map:
 [[[3 0 0 0 0]
  [0 0 0 1 0]
  [0 0 0 2 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]
Direction:
 tf.Tensor([[False False False  True]], shape=(1, 4), dtype=bool)
No body blocks:
 tf.Tensor([[15  5  5 14]], shape=(1, 4), dtype=uint8)
Action:  [0]
Map:
 [[[3 0 0 0 0]
  [0 0 1 2 0]
  [0 0 0 0

In [41]:

# Count the average steps per episode

n = 500
total_steps = 0
total_reward = 0
steps = 0
total_500 = 0
wins = 0

for i in range(n):
    if i % 10 == 0 and i != 0:
        print("Episode: ", i)
        
    time_step = test_env.reset()
    steps = 0
    episode_reward = 0
    while not time_step.is_last() and steps < 500:
        steps += 1
        action_step = agent.policy.action(time_step)
        time_step = test_env.step(action_step.action)
        reward = time_step.reward.numpy()[0]
        total_reward += reward
        episode_reward += reward
        
    if episode_reward == 115:
        wins += 1
    
    if steps == 500:
        total_500 += 1
    else:
        total_steps += steps
        
    if i % 10 == 0 and i != 0:
        print("Avg reward: ", total_reward / (i + 1))
        
if steps == 500:
    print("500 episodes reached")
    
print("Average steps per episode: ", total_steps / (n - total_500))
print("Average reward per episode: ", total_reward / n)
print("Total 500 episodes: ", total_500)
print("Wins: ", wins)


Episode:  10
Avg reward:  54.54545454545455
Episode:  20
Avg reward:  53.80952380952381
Episode:  30
Avg reward:  44.193548387096776
Episode:  40
Avg reward:  41.34146341463415
Episode:  50
Avg reward:  42.05882352941177
Episode:  60
Avg reward:  43.032786885245905
Episode:  70
Avg reward:  42.11267605633803
Episode:  80
Avg reward:  41.97530864197531
Episode:  90
Avg reward:  43.79120879120879
Episode:  100
Avg reward:  44.10891089108911
Episode:  110
Avg reward:  43.42342342342342
Episode:  120
Avg reward:  42.93388429752066
Episode:  130
Avg reward:  43.93129770992366
Episode:  140
Avg reward:  45.283687943262414
Episode:  150
Avg reward:  44.70198675496689
Episode:  160
Avg reward:  44.78260869565217
Episode:  170
Avg reward:  44.35672514619883
Episode:  180
Avg reward:  43.97790055248619
Episode:  190
Avg reward:  43.7434554973822
Episode:  200
Avg reward:  43.85572139303483
Episode:  210
Avg reward:  43.62559241706161
Episode:  220
Avg reward:  43.665158371040725
Episode:  230
Av

In [42]:
# Save the q network weights
tf.keras.models.save_model(q_net._model, "q_network.h5")

/var/folders/bw/_7s8wxw93cngpt5f7bg5s3hm0000gn/T/ipykernel_26610/1164216016.py:2: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  tf.keras.models.save_model(q_net._model, "q_network.h5")
