In [1]:
import numpy as np
import tensorflow as tf
from tf_agents.networks.q_network import QNetwork
import tf_agents.networks.network as network
from tf_agents.specs import tensor_spec
from snake_game import SnakeGame
from scene import Scene
from scene_longer_snake import SceneLongerSnake
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Flatten, Conv2D, Input

scene = SceneLongerSnake(init_randomly=True, snake_longer_prob=0.95, length_mean=10, length_std=2)
episodes_count = 50000
random_episodes = 20000


In [2]:
from tf_agents.environments.tf_py_environment import TFPyEnvironment

env = SnakeGame(scene)
env = TFPyEnvironment(env)


In [3]:
class MyQNetwork(network.Network):
    def __init__(self,
                 input_tensor_spec,
                 action_spec,
                 name='MyQNetwork'):
        super(MyQNetwork, self).__init__(
            input_tensor_spec=input_tensor_spec,
            state_spec=(),
            name=name)
        
        self._action_spec = action_spec
        matrix_shape = input_tensor_spec[0].shape
        obstacles_shape = input_tensor_spec[1].shape
        food_direction_shape = input_tensor_spec[2].shape
        
        input1 = Input(shape=matrix_shape)
        input2 = Input(shape=obstacles_shape) # Each value represents if there is a wall or the snake body in the direction, 0 - no wall, 1 - wall
        input3 = Input(shape=food_direction_shape) # Each value represents if the food is in the direction, 0 - no food, 1 - food
        
        conv = Conv2D(32, (2, 2), 1, activation='relu', kernel_initializer='he_normal')(input1)
        flat = Flatten()(conv)
        dense1 = Dense(128, activation='relu', kernel_initializer='he_normal')(flat)
        dense2 = Dense(32, activation='relu', kernel_initializer='he_normal')(dense1)
        
        concat = tf.keras.layers.concatenate([dense2, input2, input3])
        output = Dense(4, activation='linear')(concat)
        
        self._model = tf.keras.Model(inputs=[input1, input2, input3], outputs=output)
        
        self._model.summary()

    def call(self, observations, step_type=None, network_state=(), training=False):
        output = self._model([observations[0], observations[1], observations[2]])
        return output, network_state

q_net = MyQNetwork(
    env.observation_spec(),
    env.action_spec())


Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_1 (InputLayer)        [(None, 5, 5, 4)]            0         []                            
                                                                                                  
 conv2d (Conv2D)             (None, 4, 4, 32)             544       ['input_1[0][0]']             
                                                                                                  
 flatten (Flatten)           (None, 512)                  0         ['conv2d[0][0]']              
                                                                                                  
 dense (Dense)               (None, 128)                  65664     ['flatten[0][0]']             
                                                                                              

In [4]:
# Create the agent
from tf_agents.agents.dqn.dqn_agent import DdqnAgent
from tensorflow import keras
from keras.optimizers.legacy import Adam
from keras.losses import Huber
from tf_agents.trajectories import TimeStep

train_step_counter = tf.Variable(0)
optimizer = Adam(learning_rate=0.003)

epsilon = keras.optimizers.schedules.PolynomialDecay(
    initial_learning_rate=0.1,
    decay_steps=episodes_count,
    end_learning_rate=0.01
)

agent = DdqnAgent(
    time_step_spec=env.time_step_spec(),
    action_spec=env.action_spec(),
    q_network=q_net,
    optimizer=optimizer,
    td_errors_loss_fn=Huber(reduction="none"),
    gamma=tf.constant(0.95, dtype=tf.float32),
    train_step_counter=train_step_counter,
    epsilon_greedy=lambda: epsilon(train_step_counter)
)


Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_4 (InputLayer)        [(None, 5, 5, 4)]            0         []                            
                                                                                                  
 conv2d_1 (Conv2D)           (None, 4, 4, 32)             544       ['input_4[0][0]']             
                                                                                                  
 flatten_1 (Flatten)         (None, 512)                  0         ['conv2d_1[0][0]']            
                                                                                                  
 dense_3 (Dense)             (None, 128)                  65664     ['flatten_1[0][0]']           
                                                                                            

In [5]:
# Create the replay buffer
from tf_agents.replay_buffers import tf_uniform_replay_buffer

replay_buffer = tf_uniform_replay_buffer.TFUniformReplayBuffer(
    data_spec=agent.collect_data_spec,
    batch_size=env.batch_size,
    max_length=100000
)


In [6]:
# Create the training metrics
from tf_agents.metrics import tf_metrics

train_metrics = [
    tf_metrics.NumberOfEpisodes(),
    tf_metrics.EnvironmentSteps(),
    tf_metrics.AverageReturnMetric(),
    tf_metrics.AverageEpisodeLengthMetric()
]


In [7]:
# Create the driver
from tf_agents.drivers import dynamic_step_driver

collect_driver = dynamic_step_driver.DynamicStepDriver(
    env,
    policy=agent.collect_policy,
    observers=[replay_buffer.add_batch] + train_metrics,
    num_steps=2
)

# Run a random policy to fill the replay buffer
from tf_agents.policies.random_tf_policy import RandomTFPolicy

initial_collect_policy = RandomTFPolicy(env.time_step_spec(), env.action_spec())
init_driver = dynamic_step_driver.DynamicStepDriver(
    env,
    policy=initial_collect_policy,
    observers=[replay_buffer.add_batch],
    num_steps=random_episodes
)

final_time_step, final_policy_state = init_driver.run()


In [8]:
# Create the dataset
dataset = replay_buffer.as_dataset(
    sample_batch_size=64,
    num_steps=2, # Capaz cambiar esto
    num_parallel_calls=5
).prefetch(5)


Instructions for updating:
Use `as_dataset(..., single_deterministic_pass=False) instead.


In [9]:

# Create the training loop

from tf_agents.utils.common import function
from tf_agents.trajectories import trajectory
from tf_agents.eval.metric_utils import log_metrics
import logging

logging.getLogger().setLevel(logging.INFO)

collect_driver.run = function(collect_driver.run)
agent.train = function(agent.train)

def train_agent(n_iterations):
    time_step = None
    policy_state = agent.collect_policy.get_initial_state(env.batch_size)
    iterator = iter(dataset)
    for iteration in range(n_iterations):
        time_step, policy_state = collect_driver.run(time_step, policy_state)
        trajectories, buffer_info = next(iterator)
        train_loss = agent.train(trajectories)
        if iteration % 1000 == 0:
            print("Iteration: ", iteration)
            print("Replay buffer len: " + str(replay_buffer.num_frames().numpy()))
            log_metrics(train_metrics)


In [10]:
train_agent(episodes_count)


Instructions for updating:
back_prop=False is deprecated. Consider using tf.stop_gradient instead.
Instead of:
results = tf.foldr(fn, elems, back_prop=False)
Use:
results = tf.nest.map_structure(tf.stop_gradient, tf.foldr(fn, elems))


INFO:absl: 
		 NumberOfEpisodes = 0
		 EnvironmentSteps = 2
		 AverageReturn = 0.0
		 AverageEpisodeLength = 0.0


Iteration:  0
Replay buffer len: 43514


INFO:absl: 
		 NumberOfEpisodes = 335
		 EnvironmentSteps = 2002
		 AverageReturn = -12638.5
		 AverageEpisodeLength = 7.900000095367432


Iteration:  1000
Replay buffer len: 45849


INFO:absl: 
		 NumberOfEpisodes = 471
		 EnvironmentSteps = 4002
		 AverageReturn = -17297.0
		 AverageEpisodeLength = 26.5


Iteration:  2000
Replay buffer len: 47985


INFO:absl: 
		 NumberOfEpisodes = 647
		 EnvironmentSteps = 6002
		 AverageReturn = -23053.0
		 AverageEpisodeLength = 7.699999809265137


Iteration:  3000
Replay buffer len: 50161


INFO:absl: 
		 NumberOfEpisodes = 781
		 EnvironmentSteps = 8002
		 AverageReturn = -27078.0
		 AverageEpisodeLength = 14.800000190734863


Iteration:  4000
Replay buffer len: 52295


INFO:absl: 
		 NumberOfEpisodes = 927
		 EnvironmentSteps = 10002
		 AverageReturn = -31263.0
		 AverageEpisodeLength = 16.100000381469727


Iteration:  5000
Replay buffer len: 54441


INFO:absl: 
		 NumberOfEpisodes = 1070
		 EnvironmentSteps = 12002
		 AverageReturn = -35153.0
		 AverageEpisodeLength = 16.600000381469727


Iteration:  6000
Replay buffer len: 56584


INFO:absl: 
		 NumberOfEpisodes = 1207
		 EnvironmentSteps = 14002
		 AverageReturn = -38786.5
		 AverageEpisodeLength = 11.800000190734863


Iteration:  7000
Replay buffer len: 58721


INFO:absl: 
		 NumberOfEpisodes = 1350
		 EnvironmentSteps = 16002
		 AverageReturn = -42694.0
		 AverageEpisodeLength = 19.399999618530273


Iteration:  8000
Replay buffer len: 60864


INFO:absl: 
		 NumberOfEpisodes = 1478
		 EnvironmentSteps = 18002
		 AverageReturn = -45881.5
		 AverageEpisodeLength = 7.599999904632568


Iteration:  9000
Replay buffer len: 62992


INFO:absl: 
		 NumberOfEpisodes = 1592
		 EnvironmentSteps = 20002
		 AverageReturn = -48505.0
		 AverageEpisodeLength = 17.200000762939453


Iteration:  10000
Replay buffer len: 65106


INFO:absl: 
		 NumberOfEpisodes = 1740
		 EnvironmentSteps = 22002
		 AverageReturn = -52607.5
		 AverageEpisodeLength = 9.800000190734863


Iteration:  11000
Replay buffer len: 67254


INFO:absl: 
		 NumberOfEpisodes = 1868
		 EnvironmentSteps = 24002
		 AverageReturn = -55740.5
		 AverageEpisodeLength = 15.600000381469727


Iteration:  12000
Replay buffer len: 69382


INFO:absl: 
		 NumberOfEpisodes = 1975
		 EnvironmentSteps = 26002
		 AverageReturn = -58134.0
		 AverageEpisodeLength = 13.399999618530273


Iteration:  13000
Replay buffer len: 71489


INFO:absl: 
		 NumberOfEpisodes = 2096
		 EnvironmentSteps = 28002
		 AverageReturn = -61244.5
		 AverageEpisodeLength = 13.300000190734863


Iteration:  14000
Replay buffer len: 73609


INFO:absl: 
		 NumberOfEpisodes = 2218
		 EnvironmentSteps = 30002
		 AverageReturn = -64353.5
		 AverageEpisodeLength = 20.200000762939453


Iteration:  15000
Replay buffer len: 75732


INFO:absl: 
		 NumberOfEpisodes = 2347
		 EnvironmentSteps = 32002
		 AverageReturn = -67592.0
		 AverageEpisodeLength = 14.199999809265137


Iteration:  16000
Replay buffer len: 77861


INFO:absl: 
		 NumberOfEpisodes = 2466
		 EnvironmentSteps = 34002
		 AverageReturn = -70383.0
		 AverageEpisodeLength = 12.899999618530273


Iteration:  17000
Replay buffer len: 79980


INFO:absl: 
		 NumberOfEpisodes = 2565
		 EnvironmentSteps = 36002
		 AverageReturn = -72515.0
		 AverageEpisodeLength = 23.700000762939453


Iteration:  18000
Replay buffer len: 82079


INFO:absl: 
		 NumberOfEpisodes = 2665
		 EnvironmentSteps = 38002
		 AverageReturn = -74664.0
		 AverageEpisodeLength = 16.100000381469727


Iteration:  19000
Replay buffer len: 84179


INFO:absl: 
		 NumberOfEpisodes = 2773
		 EnvironmentSteps = 40002
		 AverageReturn = -77067.0
		 AverageEpisodeLength = 18.799999237060547


Iteration:  20000
Replay buffer len: 86287


INFO:absl: 
		 NumberOfEpisodes = 2880
		 EnvironmentSteps = 42002
		 AverageReturn = -79382.5
		 AverageEpisodeLength = 14.100000381469727


Iteration:  21000
Replay buffer len: 88394


INFO:absl: 
		 NumberOfEpisodes = 2957
		 EnvironmentSteps = 44002
		 AverageReturn = -80675.0
		 AverageEpisodeLength = 22.399999618530273


Iteration:  22000
Replay buffer len: 90471


INFO:absl: 
		 NumberOfEpisodes = 3069
		 EnvironmentSteps = 46002
		 AverageReturn = -83135.5
		 AverageEpisodeLength = 9.199999809265137


Iteration:  23000
Replay buffer len: 92583


INFO:absl: 
		 NumberOfEpisodes = 3166
		 EnvironmentSteps = 48002
		 AverageReturn = -85080.5
		 AverageEpisodeLength = 9.699999809265137


Iteration:  24000
Replay buffer len: 94680


INFO:absl: 
		 NumberOfEpisodes = 3255
		 EnvironmentSteps = 50002
		 AverageReturn = -86831.5
		 AverageEpisodeLength = 23.299999237060547


Iteration:  25000
Replay buffer len: 96769


INFO:absl: 
		 NumberOfEpisodes = 3340
		 EnvironmentSteps = 52002
		 AverageReturn = -88534.5
		 AverageEpisodeLength = 27.5


Iteration:  26000
Replay buffer len: 98854


INFO:absl: 
		 NumberOfEpisodes = 3423
		 EnvironmentSteps = 54002
		 AverageReturn = -90009.0
		 AverageEpisodeLength = 23.5


Iteration:  27000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 3511
		 EnvironmentSteps = 56002
		 AverageReturn = -91528.0
		 AverageEpisodeLength = 17.799999237060547


Iteration:  28000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 3602
		 EnvironmentSteps = 58002
		 AverageReturn = -93164.0
		 AverageEpisodeLength = 21.100000381469727


Iteration:  29000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 3677
		 EnvironmentSteps = 60002
		 AverageReturn = -94169.0
		 AverageEpisodeLength = 21.100000381469727


Iteration:  30000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 3765
		 EnvironmentSteps = 62002
		 AverageReturn = -95876.5
		 AverageEpisodeLength = 22.200000762939453


Iteration:  31000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 3861
		 EnvironmentSteps = 64002
		 AverageReturn = -97628.5
		 AverageEpisodeLength = 7.800000190734863


Iteration:  32000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 3949
		 EnvironmentSteps = 66002
		 AverageReturn = -99124.0
		 AverageEpisodeLength = 15.800000190734863


Iteration:  33000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 4027
		 EnvironmentSteps = 68002
		 AverageReturn = -100384.5
		 AverageEpisodeLength = 24.600000381469727


Iteration:  34000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 4121
		 EnvironmentSteps = 70002
		 AverageReturn = -102109.5
		 AverageEpisodeLength = 18.899999618530273


Iteration:  35000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 4191
		 EnvironmentSteps = 72002
		 AverageReturn = -103093.0
		 AverageEpisodeLength = 25.899999618530273


Iteration:  36000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 4269
		 EnvironmentSteps = 74002
		 AverageReturn = -104247.0
		 AverageEpisodeLength = 41.599998474121094


Iteration:  37000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 4344
		 EnvironmentSteps = 76002
		 AverageReturn = -105282.5
		 AverageEpisodeLength = 44.70000076293945


Iteration:  38000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 4415
		 EnvironmentSteps = 78002
		 AverageReturn = -106104.5
		 AverageEpisodeLength = 27.600000381469727


Iteration:  39000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 4486
		 EnvironmentSteps = 80002
		 AverageReturn = -106968.5
		 AverageEpisodeLength = 22.0


Iteration:  40000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 4547
		 EnvironmentSteps = 82002
		 AverageReturn = -107626.5
		 AverageEpisodeLength = 31.5


Iteration:  41000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 4615
		 EnvironmentSteps = 84002
		 AverageReturn = -108393.0
		 AverageEpisodeLength = 33.400001525878906


Iteration:  42000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 4691
		 EnvironmentSteps = 86002
		 AverageReturn = -109485.0
		 AverageEpisodeLength = 23.899999618530273


Iteration:  43000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 4752
		 EnvironmentSteps = 88002
		 AverageReturn = -109826.5
		 AverageEpisodeLength = 24.100000381469727


Iteration:  44000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 4814
		 EnvironmentSteps = 90002
		 AverageReturn = -110333.0
		 AverageEpisodeLength = 29.899999618530273


Iteration:  45000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 4872
		 EnvironmentSteps = 92002
		 AverageReturn = -110607.0
		 AverageEpisodeLength = 34.599998474121094


Iteration:  46000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 4931
		 EnvironmentSteps = 94002
		 AverageReturn = -110920.5
		 AverageEpisodeLength = 38.20000076293945


Iteration:  47000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 4992
		 EnvironmentSteps = 96002
		 AverageReturn = -111426.5
		 AverageEpisodeLength = 38.70000076293945


Iteration:  48000
Replay buffer len: 100000


INFO:absl: 
		 NumberOfEpisodes = 5049
		 EnvironmentSteps = 98002
		 AverageReturn = -111918.5
		 AverageEpisodeLength = 38.79999923706055


Iteration:  49000
Replay buffer len: 100000


In [33]:
# Evaluate the agent

test_scene = Scene(init_randomly=True)
test_env = SnakeGame(test_scene)
test_env = TFPyEnvironment(test_env)

time_step = test_env.reset()
rewards = []
steps = 0

while not time_step.is_last() and steps < 200:
    steps += 1
    print("Map:\n", np.argmax(time_step.observation[0], axis=3))
    print("Direction:\n", time_step.observation[1])
    action_step = agent.policy.action(time_step)
    print("Action: ", action_step.action.numpy())
    time_step = test_env.step(action_step.action)
    rewards.append(time_step.reward.numpy()[0])
    
print("Total reward: ", sum(rewards))
print("Total steps: ", steps)


Map:
 [[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 3 0 0]
  [0 1 0 0 0]
  [0 2 0 0 0]]]
Direction:
 tf.Tensor([[False False False  True]], shape=(1, 4), dtype=bool)
Action:  [2]
Map:
 [[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 3 0 0]
  [0 2 1 0 0]
  [0 0 0 0 0]]]
Direction:
 tf.Tensor([[ True False False False]], shape=(1, 4), dtype=bool)
Action:  [1]
Map:
 [[[0 0 0 0 0]
  [0 3 0 0 0]
  [0 0 1 0 0]
  [0 2 2 0 0]
  [0 0 0 0 0]]]
Direction:
 tf.Tensor([[False False False  True]], shape=(1, 4), dtype=bool)
Action:  [0]
Map:
 [[[0 0 0 0 0]
  [0 3 0 0 0]
  [0 1 2 0 0]
  [0 0 2 0 0]
  [0 0 0 0 0]]]
Direction:
 tf.Tensor([[False False  True False]], shape=(1, 4), dtype=bool)
Action:  [1]
Map:
 [[[0 0 0 0 0]
  [0 1 0 0 0]
  [0 2 2 0 0]
  [0 0 2 0 0]
  [0 0 0 3 0]]]
Direction:
 tf.Tensor([[False False False  True]], shape=(1, 4), dtype=bool)
Action:  [2]
Map:
 [[[0 0 0 0 0]
  [0 2 1 0 0]
  [0 2 2 0 0]
  [0 0 0 0 0]
  [0 0 0 3 0]]]
Direction:
 tf.Tensor([[ True False False False]], shape=(1, 4), dtype=bool)
Actio

In [32]:

# Count the average steps per episode

n = 500
total_steps = 0
total_reward = 0
steps = 0
total_500 = 0
wins = 0

for i in range(n):
    if i % 10 == 0 and i != 0:
        print("Episode: ", i)
        
    time_step = test_env.reset()
    steps = 0
    episode_reward = 0
    while not time_step.is_last() and steps < 500:
        steps += 1
        action_step = agent.policy.action(time_step)
        time_step = test_env.step(action_step.action)
        reward = time_step.reward.numpy()[0]
        total_reward += reward
        episode_reward += reward
        
    if episode_reward == 115:
        wins += 1
    
    if steps == 500:
        total_500 += 1
    else:
        total_steps += steps
        
    if i % 10 == 0 and i != 0:
        print("Avg reward: ", total_reward / (i + 1))
        
if steps == 500:
    print("500 episodes reached")
    
print("Average steps per episode: ", total_steps / (n - total_500))
print("Average reward per episode: ", total_reward / n)
print("Total 500 episodes: ", total_500)
print("Wins: ", wins)


Episode:  10
Avg reward:  40.0
Episode:  20
Avg reward:  38.57142857142857
Episode:  30
Avg reward:  39.516129032258064
Episode:  40
Avg reward:  38.53658536585366
Episode:  50
Avg reward:  37.64705882352941
Episode:  60
Avg reward:  37.78688524590164
Episode:  70
Avg reward:  36.76056338028169
Episode:  80
Avg reward:  38.20987654320987
Episode:  90
Avg reward:  37.582417582417584
Episode:  100
Avg reward:  36.633663366336634
Episode:  110
Avg reward:  37.027027027027025
Episode:  120
Avg reward:  36.611570247933884
Episode:  130
Avg reward:  37.51908396946565
Episode:  140
Avg reward:  37.4468085106383
Episode:  150
Avg reward:  38.50993377483444
Episode:  160
Avg reward:  38.1055900621118
Episode:  170
Avg reward:  39.21052631578947
Episode:  180
Avg reward:  39.58563535911602
Episode:  190
Avg reward:  39.81675392670157
Episode:  200
Avg reward:  40.0
Episode:  210
Avg reward:  40.426540284360186
Episode:  220
Avg reward:  40.36199095022624
Episode:  230
Avg reward:  41.06060606060

In [30]:
115.0 == 115

True

In [13]:
# Save the q network weights
tf.keras.models.save_model(q_net._model, "q_network.h5")

/var/folders/bw/_7s8wxw93cngpt5f7bg5s3hm0000gn/T/ipykernel_21588/1164216016.py:2: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  tf.keras.models.save_model(q_net._model, "q_network.h5")
