In [1]:
import numpy as np
import tensorflow as tf
from tf_agents.networks.q_network import QNetwork
import tf_agents.networks.network as network
from tf_agents.specs import tensor_spec
from snake_game import SnakeGame
from scene import Scene
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Flatten, Conv2D, Input

scene = Scene(init_randomly=True)
episodes_count = 50000
random_episodes = 10000


In [2]:
from tf_agents.environments.tf_py_environment import TFPyEnvironment

env = SnakeGame(scene)
env = TFPyEnvironment(env)


In [8]:
class MyQNetwork(network.Network):
    def __init__(self,
                 input_tensor_spec,
                 action_spec,
                 name='MyQNetwork'):
        super(MyQNetwork, self).__init__(
            input_tensor_spec=input_tensor_spec,
            state_spec=(),
            name=name)
        
        self._action_spec = action_spec
        matrix_shape = input_tensor_spec["scene"].shape
        
        input1 = Input(shape=matrix_shape)
        input2 = Input(shape=(4,)) # Each value represents if there is a wall or the snake body in the direction, 0 - no wall, 1 - wall
        
        conv = Conv2D(16, (2, 2), 1, activation='relu', kernel_initializer='he_normal')(input1)
        flat = Flatten()(conv)
        dense1 = Dense(64, activation='relu', kernel_initializer='he_normal')(flat)
        dense2 = Dense(16, activation='relu', kernel_initializer='he_normal')(dense1)
        
        concat = tf.keras.layers.concatenate([dense2, input2])
        output = Dense(4, activation='linear')(concat)
        
        self._model = tf.keras.Model(inputs=[input1, input2], outputs=output)
        
        print(self._model.summary())

    def call(self, observations, step_type=None, network_state=(), training=False):
        output = self._model(observations)
        return output, network_state

q_net = MyQNetwork(
    env.observation_spec(),
    env.action_spec())


Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_5 (InputLayer)        [(None, 5, 5, 4)]            0         []                            
                                                                                                  
 conv2d_2 (Conv2D)           (None, 4, 4, 16)             272       ['input_5[0][0]']             
                                                                                                  
 flatten_1 (Flatten)         (None, 256)                  0         ['conv2d_2[0][0]']            
                                                                                                  
 dense_3 (Dense)             (None, 64)                   16448     ['flatten_1[0][0]']           
                                                                                              

In [9]:
# Create the agent
from tf_agents.agents.dqn.dqn_agent import DdqnAgent
from tensorflow import keras
from keras.optimizers import Adam
from keras.losses import Huber
from tf_agents.trajectories import TimeStep

train_step_counter = tf.Variable(0)
optimizer = Adam(learning_rate=0.003)

epsilon = keras.optimizers.schedules.PolynomialDecay(
    initial_learning_rate=0.1,
    decay_steps=episodes_count,
    end_learning_rate=0.01
)

agent = DdqnAgent(
    time_step_spec=env.time_step_spec(),
    action_spec=env.action_spec(),
    q_network=q_net,
    optimizer=optimizer,
    td_errors_loss_fn=Huber(reduction="none"),
    gamma=tf.constant(0.95, dtype=tf.float32),
    train_step_counter=train_step_counter,
    epsilon_greedy=lambda: epsilon(train_step_counter)
)


ValueError: Exception encountered when calling layer 'MyQNetwork' (type MyQNetwork).

Missing data for input "input_5". You passed a data dictionary with keys ['scene', 'array_1d']. Expected the following keys: ['input_5', 'input_6']

Call arguments received by layer 'MyQNetwork' (type MyQNetwork):
  • observations={'scene': 'tf.Tensor(shape=(1, 5, 5, 4), dtype=float32)', 'array_1d': 'tf.Tensor(shape=(1, 4), dtype=bool)'}
  • step_type=tf.Tensor(shape=(1,), dtype=int32)
  • network_state=()
  • training=False
  In call to configurable 'DqnAgent' (<class 'tf_agents.agents.dqn.dqn_agent.DqnAgent'>)
  In call to configurable 'DdqnAgent' (<class 'tf_agents.agents.dqn.dqn_agent.DdqnAgent'>)

In [5]:
# Create the replay buffer
from tf_agents.replay_buffers import tf_uniform_replay_buffer

replay_buffer = tf_uniform_replay_buffer.TFUniformReplayBuffer(
    data_spec=agent.collect_data_spec,
    batch_size=env.batch_size,
    max_length=100000
)


In [6]:
# Create the training metrics
from tf_agents.metrics import tf_metrics

train_metrics = [
    tf_metrics.NumberOfEpisodes(),
    tf_metrics.EnvironmentSteps(),
    tf_metrics.AverageReturnMetric(),
    tf_metrics.AverageEpisodeLengthMetric()
]


In [7]:
# Create the driver
from tf_agents.drivers import dynamic_step_driver

collect_driver = dynamic_step_driver.DynamicStepDriver(
    env,
    policy=agent.collect_policy,
    observers=[replay_buffer.add_batch] + train_metrics,
    num_steps=4
)

# Run a random policy to fill the replay buffer
from tf_agents.policies.random_tf_policy import RandomTFPolicy

initial_collect_policy = RandomTFPolicy(env.time_step_spec(), env.action_spec())
init_driver = dynamic_step_driver.DynamicStepDriver(
    env,
    policy=initial_collect_policy,
    observers=[replay_buffer.add_batch],
    num_steps=random_episodes
)

final_time_step, final_policy_state = init_driver.run()


In [8]:
# Create the dataset
dataset = replay_buffer.as_dataset(
    sample_batch_size=64,
    num_steps=2, # Capaz cambiar esto
    num_parallel_calls=3
).prefetch(3)


Instructions for updating:
Use `as_dataset(..., single_deterministic_pass=False) instead.


Instructions for updating:
Use `as_dataset(..., single_deterministic_pass=False) instead.


In [9]:
# Create the training loop

from tf_agents.utils.common import function
from tf_agents.trajectories import trajectory
from tf_agents.eval.metric_utils import log_metrics
import logging

logging.getLogger().setLevel(logging.INFO)

collect_driver.run = function(collect_driver.run)
agent.train = function(agent.train)

def train_agent(n_iterations):
    time_step = None
    policy_state = agent.collect_policy.get_initial_state(env.batch_size)
    iterator = iter(dataset)
    for iteration in range(n_iterations):
        time_step, policy_state = collect_driver.run(time_step, policy_state)
        trajectories, buffer_info = next(iterator)
        train_loss = agent.train(trajectories)
        if iteration % 1000 == 0:
            print("Iteration: ", iteration)
            log_metrics(train_metrics)


In [10]:
train_agent(episodes_count)


Instructions for updating:
back_prop=False is deprecated. Consider using tf.stop_gradient instead.
Instead of:
results = tf.foldr(fn, elems, back_prop=False)
Use:
results = tf.nest.map_structure(tf.stop_gradient, tf.foldr(fn, elems))


Instructions for updating:
back_prop=False is deprecated. Consider using tf.stop_gradient instead.
Instead of:
results = tf.foldr(fn, elems, back_prop=False)
Use:
results = tf.nest.map_structure(tf.stop_gradient, tf.foldr(fn, elems))
INFO:absl: 
		 NumberOfEpisodes = 1
		 EnvironmentSteps = 4
		 AverageReturn = -18.0
		 AverageEpisodeLength = 4.0


Iteration:  0


INFO:absl: 
		 NumberOfEpisodes = 713
		 EnvironmentSteps = 4004
		 AverageReturn = -10842.2998046875
		 AverageEpisodeLength = 28.200000762939453


Iteration:  1000


INFO:absl: 
		 NumberOfEpisodes = 865
		 EnvironmentSteps = 8004
		 AverageReturn = -11710.5
		 AverageEpisodeLength = 15.300000190734863


Iteration:  2000


INFO:absl: 
		 NumberOfEpisodes = 1070
		 EnvironmentSteps = 12004
		 AverageReturn = -10784.2998046875
		 AverageEpisodeLength = 20.5


Iteration:  3000


INFO:absl: 
		 NumberOfEpisodes = 1241
		 EnvironmentSteps = 16004
		 AverageReturn = -9240.900390625
		 AverageEpisodeLength = 29.700000762939453


Iteration:  4000


INFO:absl: 
		 NumberOfEpisodes = 1409
		 EnvironmentSteps = 20004
		 AverageReturn = -6278.89990234375
		 AverageEpisodeLength = 21.100000381469727


Iteration:  5000


INFO:absl: 
		 NumberOfEpisodes = 1592
		 EnvironmentSteps = 24004
		 AverageReturn = -1565.199951171875
		 AverageEpisodeLength = 19.100000381469727


Iteration:  6000


INFO:absl: 
		 NumberOfEpisodes = 1770
		 EnvironmentSteps = 28004
		 AverageReturn = 6006.0
		 AverageEpisodeLength = 21.299999237060547


Iteration:  7000


INFO:absl: 
		 NumberOfEpisodes = 1985
		 EnvironmentSteps = 32004
		 AverageReturn = 18726.5
		 AverageEpisodeLength = 16.299999237060547


Iteration:  8000


INFO:absl: 
		 NumberOfEpisodes = 2259
		 EnvironmentSteps = 36004
		 AverageReturn = 35247.69921875
		 AverageEpisodeLength = 22.5


Iteration:  9000


INFO:absl: 
		 NumberOfEpisodes = 2500
		 EnvironmentSteps = 40004
		 AverageReturn = 52717.5
		 AverageEpisodeLength = 17.799999237060547


Iteration:  10000


INFO:absl: 
		 NumberOfEpisodes = 2728
		 EnvironmentSteps = 44004
		 AverageReturn = 70995.1015625
		 AverageEpisodeLength = 21.200000762939453


Iteration:  11000


INFO:absl: 
		 NumberOfEpisodes = 2961
		 EnvironmentSteps = 48004
		 AverageReturn = 89510.6015625
		 AverageEpisodeLength = 21.5


Iteration:  12000


INFO:absl: 
		 NumberOfEpisodes = 3203
		 EnvironmentSteps = 52004
		 AverageReturn = 108915.6015625
		 AverageEpisodeLength = 20.100000381469727


Iteration:  13000


INFO:absl: 
		 NumberOfEpisodes = 3426
		 EnvironmentSteps = 56004
		 AverageReturn = 128021.3984375
		 AverageEpisodeLength = 19.799999237060547


Iteration:  14000


INFO:absl: 
		 NumberOfEpisodes = 3665
		 EnvironmentSteps = 60004
		 AverageReturn = 146974.40625
		 AverageEpisodeLength = 12.800000190734863


Iteration:  15000


INFO:absl: 
		 NumberOfEpisodes = 3886
		 EnvironmentSteps = 64004
		 AverageReturn = 166073.296875
		 AverageEpisodeLength = 20.600000381469727


Iteration:  16000


INFO:absl: 
		 NumberOfEpisodes = 4112
		 EnvironmentSteps = 68004
		 AverageReturn = 184662.09375
		 AverageEpisodeLength = 29.100000381469727


Iteration:  17000


INFO:absl: 
		 NumberOfEpisodes = 4330
		 EnvironmentSteps = 72004
		 AverageReturn = 203929.5
		 AverageEpisodeLength = 19.899999618530273


Iteration:  18000


INFO:absl: 
		 NumberOfEpisodes = 4555
		 EnvironmentSteps = 76004
		 AverageReturn = 223698.296875
		 AverageEpisodeLength = 17.899999618530273


Iteration:  19000


INFO:absl: 
		 NumberOfEpisodes = 4775
		 EnvironmentSteps = 80004
		 AverageReturn = 242319.90625
		 AverageEpisodeLength = 17.100000381469727


Iteration:  20000


INFO:absl: 
		 NumberOfEpisodes = 4977
		 EnvironmentSteps = 84004
		 AverageReturn = 262007.5
		 AverageEpisodeLength = 18.700000762939453


Iteration:  21000


INFO:absl: 
		 NumberOfEpisodes = 5195
		 EnvironmentSteps = 88004
		 AverageReturn = 282395.1875
		 AverageEpisodeLength = 16.200000762939453


Iteration:  22000


INFO:absl: 
		 NumberOfEpisodes = 5402
		 EnvironmentSteps = 92004
		 AverageReturn = 301500.6875
		 AverageEpisodeLength = 18.399999618530273


Iteration:  23000


INFO:absl: 
		 NumberOfEpisodes = 5606
		 EnvironmentSteps = 96004
		 AverageReturn = 321621.3125
		 AverageEpisodeLength = 16.600000381469727


Iteration:  24000


INFO:absl: 
		 NumberOfEpisodes = 5842
		 EnvironmentSteps = 100004
		 AverageReturn = 342219.8125
		 AverageEpisodeLength = 15.5


Iteration:  25000


INFO:absl: 
		 NumberOfEpisodes = 6083
		 EnvironmentSteps = 104004
		 AverageReturn = 361693.59375
		 AverageEpisodeLength = 15.800000190734863


Iteration:  26000


INFO:absl: 
		 NumberOfEpisodes = 6296
		 EnvironmentSteps = 108004
		 AverageReturn = 382396.09375
		 AverageEpisodeLength = 23.700000762939453


Iteration:  27000


INFO:absl: 
		 NumberOfEpisodes = 6511
		 EnvironmentSteps = 112004
		 AverageReturn = 403843.1875
		 AverageEpisodeLength = 17.700000762939453


Iteration:  28000


INFO:absl: 
		 NumberOfEpisodes = 6731
		 EnvironmentSteps = 116004
		 AverageReturn = 424125.8125
		 AverageEpisodeLength = 21.0


Iteration:  29000


INFO:absl: 
		 NumberOfEpisodes = 6930
		 EnvironmentSteps = 120004
		 AverageReturn = 444956.40625
		 AverageEpisodeLength = 18.799999237060547


Iteration:  30000


INFO:absl: 
		 NumberOfEpisodes = 7144
		 EnvironmentSteps = 124004
		 AverageReturn = 465658.90625
		 AverageEpisodeLength = 19.899999618530273


Iteration:  31000


INFO:absl: 
		 NumberOfEpisodes = 7344
		 EnvironmentSteps = 128004
		 AverageReturn = 486562.59375
		 AverageEpisodeLength = 17.700000762939453


Iteration:  32000


INFO:absl: 
		 NumberOfEpisodes = 7560
		 EnvironmentSteps = 132004
		 AverageReturn = 508596.3125
		 AverageEpisodeLength = 19.799999237060547


Iteration:  33000


INFO:absl: 
		 NumberOfEpisodes = 7760
		 EnvironmentSteps = 136004
		 AverageReturn = 529354.6875
		 AverageEpisodeLength = 17.200000762939453


Iteration:  34000


INFO:absl: 
		 NumberOfEpisodes = 7949
		 EnvironmentSteps = 140004
		 AverageReturn = 550497.6875
		 AverageEpisodeLength = 20.100000381469727


Iteration:  35000


INFO:absl: 
		 NumberOfEpisodes = 8154
		 EnvironmentSteps = 144004
		 AverageReturn = 571727.5
		 AverageEpisodeLength = 20.399999618530273


Iteration:  36000


INFO:absl: 
		 NumberOfEpisodes = 8352
		 EnvironmentSteps = 148004
		 AverageReturn = 592313.875
		 AverageEpisodeLength = 15.899999618530273


Iteration:  37000


INFO:absl: 
		 NumberOfEpisodes = 8561
		 EnvironmentSteps = 152004
		 AverageReturn = 613398.875
		 AverageEpisodeLength = 14.899999618530273


Iteration:  38000


INFO:absl: 
		 NumberOfEpisodes = 8761
		 EnvironmentSteps = 156004
		 AverageReturn = 635592.5
		 AverageEpisodeLength = 16.200000762939453


Iteration:  39000


INFO:absl: 
		 NumberOfEpisodes = 8940
		 EnvironmentSteps = 160004
		 AverageReturn = 656670.5
		 AverageEpisodeLength = 34.0


Iteration:  40000


INFO:absl: 
		 NumberOfEpisodes = 9134
		 EnvironmentSteps = 164004
		 AverageReturn = 679037.0
		 AverageEpisodeLength = 19.5


Iteration:  41000


INFO:absl: 
		 NumberOfEpisodes = 9318
		 EnvironmentSteps = 168004
		 AverageReturn = 700262.3125
		 AverageEpisodeLength = 23.200000762939453


Iteration:  42000


INFO:absl: 
		 NumberOfEpisodes = 9495
		 EnvironmentSteps = 172004
		 AverageReturn = 722991.3125
		 AverageEpisodeLength = 24.399999618530273


Iteration:  43000


INFO:absl: 
		 NumberOfEpisodes = 9674
		 EnvironmentSteps = 176004
		 AverageReturn = 745572.5
		 AverageEpisodeLength = 19.600000381469727


Iteration:  44000


INFO:absl: 
		 NumberOfEpisodes = 9865
		 EnvironmentSteps = 180004
		 AverageReturn = 766755.1875
		 AverageEpisodeLength = 27.200000762939453


Iteration:  45000


INFO:absl: 
		 NumberOfEpisodes = 10037
		 EnvironmentSteps = 184004
		 AverageReturn = 788294.8125
		 AverageEpisodeLength = 24.399999618530273


Iteration:  46000


INFO:absl: 
		 NumberOfEpisodes = 10218
		 EnvironmentSteps = 188004
		 AverageReturn = 811772.3125
		 AverageEpisodeLength = 17.100000381469727


Iteration:  47000


INFO:absl: 
		 NumberOfEpisodes = 10391
		 EnvironmentSteps = 192004
		 AverageReturn = 834385.375
		 AverageEpisodeLength = 27.0


Iteration:  48000


INFO:absl: 
		 NumberOfEpisodes = 10561
		 EnvironmentSteps = 196004
		 AverageReturn = 856874.5
		 AverageEpisodeLength = 16.600000381469727


Iteration:  49000


In [14]:
# Evaluate the agent

time_step = env.reset()
rewards = []
steps = 0

while not time_step.is_last() and steps < 200:
    steps += 1
    print("Map:\n", np.argmax(time_step.observation.numpy(), axis=3))
    action_step = agent.policy.action(time_step)
    print("Action: ", action_step.action.numpy())
    time_step = env.step(action_step.action)
    rewards.append(time_step.reward.numpy()[0])
    
print("Total reward: ", sum(rewards))
print("Total steps: ", steps)


Map:
 [[[0 0 0 3 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 2 1 0]
  [0 0 0 0 0]]]
Action:  [1]
Map:
 [[[0 0 0 3 0]
  [0 0 0 0 0]
  [0 0 0 1 0]
  [0 0 0 2 0]
  [0 0 0 0 0]]]
Action:  [1]
Map:
 [[[0 0 0 3 0]
  [0 0 0 1 0]
  [0 0 0 2 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]
Action:  [1]
Map:
 [[[0 0 0 1 0]
  [0 3 0 2 0]
  [0 0 0 2 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]
Action:  [0]
Map:
 [[[0 0 1 2 0]
  [0 3 0 2 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]
Action:  [0]
Map:
 [[[0 1 2 2 0]
  [0 3 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]
Action:  [3]
Map:
 [[[0 2 2 2 3]
  [0 1 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]
Action:  [2]
Map:
 [[[0 2 2 0 3]
  [0 2 1 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]
Action:  [2]
Map:
 [[[0 2 0 0 3]
  [0 2 2 1 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]
Action:  [2]
Map:
 [[[0 0 0 0 3]
  [0 2 2 2 1]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]
Action:  [1]
Map:
 [[[0 0 0 0 1]
  [0 2 2 2 2]
  [0 0 3 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]
Action:  [0]

In [12]:
# Count the average steps per episode

n = 500
total_steps = 0
total_reward = 0
steps = 0
total_500 = 0

for i in range(n):
    if i % 10 == 0:
        print("Episode: ", i)
        
    time_step = env.reset()
    steps = 0
    while not time_step.is_last() and steps < 500:
        steps += 1
        action_step = agent.policy.action(time_step)
        time_step = env.step(action_step.action)
        reward = time_step.reward.numpy()[0]
        total_reward += reward
    
    if steps == 500:
        total_500 += 1
    else:
        total_steps += steps
        
if steps == 500:
    print("500 episodes reached")
    
print("Average steps per episode: ", total_steps / (n - total_500))
print("Average reward per episode: ", total_reward / n)
print("Total 500 episodes: ", total_500)


Episode:  0
Episode:  10
Episode:  20
Episode:  30
Episode:  40
Episode:  50
Episode:  60
Episode:  70
Episode:  80
Episode:  90
Episode:  100
Episode:  110
Episode:  120
Episode:  130
Episode:  140
Episode:  150
Episode:  160
Episode:  170
Episode:  180
Episode:  190
Episode:  200
Episode:  210
Episode:  220
Episode:  230
Episode:  240
Episode:  250
Episode:  260
Episode:  270
Episode:  280
Episode:  290
Episode:  300
Episode:  310
Episode:  320
Episode:  330
Episode:  340
Episode:  350
Episode:  360
Episode:  370
Episode:  380
Episode:  390
Episode:  400
Episode:  410
Episode:  420
Episode:  430
Episode:  440
Episode:  450
Episode:  460
Episode:  470
Episode:  480
Episode:  490
Average steps per episode:  28.804
Average reward per episode:  162.648
Total 500 episodes:  0


In [13]:
# Save the agent
import os
from tf_agents.policies.policy_saver import PolicySaver

saver = PolicySaver(agent.policy, batch_size=None)
saver.save("policy")


TypeError: this __dict__ descriptor does not support '_DictWrapper' objects